### ISSUE TITLE
Fails to start with "Failed to read plugins dir"

### ISSUE THREAD

**Issue by googol** [yaakapp/app#72]
Log:
```
$ RUST_BACKTRACE=full yaak-app 
[2024-09-11][09:58:33][INFO][yaak_models::plugin] Opening SQLite DB at "/home/googol/.local/share/app.yaak.desktop/db.sqlite"
[2024-09-11][09:58:33][INFO][yaak_models::plugin] Creating database file at "/home/googol/.local/share/app.yaak.desktop/db.sqlite"
[2024-09-11][09:58:33][INFO][yaak_models::plugin] Connecting to database at sqlite:///home/googol/.local/share/app.yaak.desktop/db.sqlite?mode=rwc
[2024-09-11][09:58:33][INFO][yaak_models::plugin] Running database migrations from: /usr/lib/yaak-app/migrations
[2024-09-11][09:58:33][INFO][yaak_models::plugin] Database migrations complete
thread 'main' panicked at /home/runner/work/app/app/src-tauri/yaak_plugin_runtime/src/plugin.rs:30:22:
Failed to read plugins dir: IoErr(Os { code: 2, kind: NotFound, message: "No such file or directory" })
stack backtrace:
   0:     0x5567dd6a8d15 - <unknown>
   1:     0x5567dd6d8aeb - <unknown>
   2:     0x5567dd6a4b7f - <unknown>
   3:     0x5567dd6a8aee - <unknown>
   4:     0x5567dd6aa1d9 - <unknown>
   5:     0x5567dd6a9f7a - <unknown>
   6:     0x5567dd6aa673 - <unknown>
   7:     0x5567dd6aa554 - <unknown>
   8:     0x5567dd6a91d9 - <unknown>
   9:     0x5567dd6aa287 - <unknown>
  10:     0x5567dbfd6a53 - <unknown>
  11:     0x5567dbfd6f46 - <unknown>
  12:     0x5567dc3183ee - <unknown>
  13:     0x5567dc41a2f3 - <unknown>
  14:     0x5567dc3074d9 - <unknown>
  15:     0x5567dc81078f - <unknown>
  16:     0x5567dc84bf85 - <unknown>
  17:     0x5567dc83db92 - <unknown>
  18:     0x5567dc0cc111 - <unknown>
  19:     0x5567dbfd7503 - <unknown>
  20:     0x5567dbfd7519 - <unknown>
  21:     0x5567dd69c02d - <unknown>
  22:     0x5567dbfd7565 - <unknown>
  23:     0x7f279421b14a - __libc_start_call_main
  24:     0x7f279421b20b - __libc_start_main_alias_2
  25:     0x5567dbfd7435 - <unknown>
  26:                0x0 - <unknown>

```

Running on fedora 39, Linux 6.10.7-100.fc39.x86_64.
Installed from the rpm file (version 2024.8.2)

**Comment by googol** [comment]
Sure, here's the log for 2024.9.0-beta.3-1
```
$ RUST_BACKTRACE=full yaak-app 
[2024-09-11][18:10:51][INFO][yaak_models::plugin] Opening SQLite DB at "/home/googol/.local/share/app.yaak.desktop/db.sqlite"
[2024-09-11][18:10:51][INFO][yaak_models::plugin] Creating database file at "/home/googol/.local/share/app.yaak.desktop/db.sqlite"
[2024-09-11][18:10:51][INFO][yaak_models::plugin] Connecting to database at sqlite:///home/googol/.local/share/app.yaak.desktop/db.sqlite?mode=rwc
[2024-09-11][18:10:51][INFO][yaak_models::plugin] Running database migrations from: /usr/lib/yaak-app/migrations
[2024-09-11][18:10:51][INFO][yaak_models::plugin] Database migrations complete
thread 'main' panicked at /home/runner/work/app/app/src-tauri/yaak_plugin_runtime/src/plugin.rs:31:22:
Failed to read plugins dir: "/usr/lib/yaak-app/plugins": IoErr(Os { code: 2, kind: NotFound, message: "No such file or directory" })
stack backtrace:
   0:     0x557344ac6bf5 - <unknown>
   1:     0x557344af562b - <unknown>
   2:     0x557344ac2d2f - <unknown>
   3:     0x557344ac8091 - <unknown>
   4:     0x557344ac7d6c - <unknown>
   5:     0x557344ac86f1 - <unknown>
   6:     0x557344ac8557 - <unknown>
   7:     0x557344ac70b9 - <unknown>
   8:     0x557344ac81e4 - <unknown>
   9:     0x5573433f3e83 - <unknown>
  10:     0x5573433f4356 - <unknown>
  11:     0x5573439623e4 - <unknown>
  12:     0x5573439a9418 - <unknown>
  13:     0x557343aec43c - <unknown>
  14:     0x5573439ab04c - <unknown>
  15:     0x557343731fe6 - <unknown>
  16:     0x55734376441b - <unknown>
  17:     0x557343752743 - <unknown>
  18:     0x55734384eaa1 - <unknown>
  19:     0x5573436100e9 - <unknown>
  20:     0x55734342b437 - <unknown>
  21:     0x5573433f4903 - <unknown>
  22:     0x5573433f48f9 - <unknown>
  23:     0x557344aba2c0 - <unknown>
  24:     0x5573433f4955 - <unknown>
  25:     0x7f360861b14a - __libc_start_call_main
  26:     0x7f360861b20b - __libc_start_main_alias_2
  27:     0x5573433f4825 - <unknown>
  28:                0x0 - <unknown>
  ```

**Comment by gschier** [comment]
Thanks! Is there anything at `/usr/lib/yaak-app/plugins`?

**Comment by googol** [comment]
No the directory doesn't exist. There is a `/usr/lib/yaak-app/vendored/plugins` though

```
$ tree /usr/lib/yaak-app
/usr/lib/yaak-app/
├── migrations
│   ├── 20230225181302_init.sql
│   ├── 20230319042610_sort-priority.sql
│   ├── 20230330143214_request-auth.sql
│   ├── 20230413232435_response-body-blob.sql
│   ├── 20231022205109_environments.sql
│   ├── 20231028161007_variables.sql
│   ├── 20231103004111_workspace-variables.sql
│   ├── 20231103142807_folders.sql
│   ├── 20231112180500_body_object.sql
│   ├── 20231113183810_url_params.sql
│   ├── 20231122055216_remove_body.sql
│   ├── 20240111221224_settings.sql
│   ├── 20240115193751_workspace_settings.sql
│   ├── 20240118181105_channel_setting.sql
│   ├── 20240127013915_cookies.sql
│   ├── 20240128230717_more_response_attrs.sql
│   ├── 20240203164833_grpc.sql
│   ├── 20240522031045_theme-settings.sql
│   ├── 20240529143147_more-settings.sql
│   ├── 20240607151115_open-workspace-setting.sql
│   ├── 20240814013812_fix-env-model.sql
│   ├── 20240826184943_disable-telemetry.sql
│   └── 20240829131004_plugins.sql
├── _up_
│   └── plugin-runtime
│       └── build
│           ├── index.cjs
│           └── index.worker.cjs
└── vendored
    ├── plugins
    │   ├── exporter-curl
    │   │   ├── build
    │   │   │   └── index.js
    │   │   └── package.json
    │   ├── filter-jsonpath
    │   │   ├── build
    │   │   │   └── index.js
    │   │   └── package.json
    │   ├── filter-xpath
    │   │   ├── build
    │   │   │   └── index.js
    │   │   └── package.json
    │   ├── importer-curl
    │   │   ├── build
    │   │   │   └── index.js
    │   │   └── package.json
    │   ├── importer-insomnia
    │   │   ├── build
    │   │   │   └── index.js
    │   │   └── package.json
    │   ├── importer-openapi
    │   │   ├── build
    │   │   │   └── index.js
    │   │   └── package.json
    │   ├── importer-postman
    │   │   ├── build
    │   │   │   └── index.js
    │   │   └── package.json
    │   ├── importer-yaak
    │   │   ├── build
    │   │   │   └── index.js
    │   │   └── package.json
    │   └── template-function-response
    │       ├── build
    │       │   └── index.js
    │       └── package.json
    └── protoc
        └── include
            └── google
                └── protobuf
                    ├── any.proto
                    ├── api.proto
                    ├── compiler
                    │   └── plugin.proto
                    ├── cpp_features.proto
                    ├── descriptor.proto
                    ├── duration.proto
                    ├── empty.proto
                    ├── field_mask.proto
                    ├── java_features.proto
                    ├── source_context.proto
                    ├── struct.proto
                    ├── timestamp.proto
                    ├── type.proto
                    └── wrappers.proto

30 directories, 57 files
```

**Comment by copart** [comment]
I also had same problem, fixed it by creating the directory.

However, I do see the following posted to console

```
[2024-09-12][22:00:48][INFO][yaak_plugin_runtime::nodejs] Starting plugin runtime main=/usr/lib/yaak-app/plugin-runtime/index.cjs
Spawned plugin runtime
[2024-09-12][22:00:48][INFO][tauri_app_lib] Create new window label=main_0
node:internal/modules/cjs/loader:1222
  throw err;
  ^

Error: Cannot find module '/usr/lib/yaak-app/plugin-runtime/index.cjs'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1219:15)
    at Module._load (node:internal/modules/cjs/loader:1045:27)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:215:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:158:5)
    at node:internal/main/run_main_module:30:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v22.5.1
[2024-09-12][22:00:49][INFO][tauri_app_lib::updates] Checking for updates mode=stable
```

**Comment by andrewliebenow** [comment]
```
❯ rpm --dump --package --query -- ./yaak-2024.9.1-1.x86_64.rpm | rg 'plugin-runtime'
/usr/lib/yaak/_up_/plugin-runtime/build/index.cjs 901585 1726582848 12ee2489472d926ec02d7bb00ea4e1732f383879a2a706304184f5073d53cea9 0100644 root root 0 0 0 X
/usr/lib/yaak/_up_/plugin-runtime/build/index.worker.cjs 20701 1726582848 8525870bc19105e0b195129aba59d0eb8cac0595896601dd08784041c95ffb31 0100644 root root 0 0 0 X
```

I think a "`..`" in a path is being replaced by the string "`_up_`" instead of actually navigating the path up a directory.

See:

https://github.com/yaakapp/app/blob/93633875ac9d13ec3b6d39a283902e47bcee9e93/src-tauri/tauri.conf.json#L59-L64

I think just replacing ".." with "plugins" might work.

**Comment by gschier** [comment]
I can try, but I think it might be a bug with the RPM build, since all the other Linux installers work just fine 🤷🏻

**Comment by gschier** [comment]
Can one of you let me know if this fixed the issue?

**Comment by andrewliebenow** [comment]
> Can one of you let me know if this fixed the issue?

Yes, it did. Launches and runs fine now.

And no `_up_` path segments in the .rpm:

```
❯ rpm --dump --package --query -- ./yaak-2024.10.0-1.x86_64.rpm | rg -- 'plugin-runtime'
/usr/lib/yaak/vendored/plugin-runtime/index.cjs 902736 1727298237 bc8453e6cb3e1620bf9b09c1d6df9565c7376325c76b1c1d0c683902711bc468 0100644 root root 0 0 0 X
/usr/lib/yaak/vendored/plugin-runtime/index.worker.cjs 20903 1727298237 b6fac97a732789f11d1fd75e1b54ec9a0fd485b5d05e4034b3630204b10f02a0 0100644 root root 0 0 0 X
```

**Comment by andrewliebenow** [comment]
Unrelated, but you might be able to simplify the build process and avoid vendoring `protoc` (https://github.com/yaakapp/app/blob/2be45d61019d5ce6e160d62d0a3fceffea3af56d/scripts/vendor-protoc.cjs) by using `protox`:

**Comment by andrewliebenow** [comment]
Unrelated, but you might be able to simplify your build process and avoid vendoring `protoc` (https://github.com/yaakapp/app/blob/2be45d61019d5ce6e160d62d0a3fceffea3af56d/scripts/vendor-protoc.cjs) by using `protox`:

https://github.com/andrewhickman/protox

**Comment by gschier** [comment]
Thanks for confirming @andrewliebenow!

I don't remember the exact details, but I think the issue was that libs like protox went strait to generating Rust types. Yaak needs to be able to dynamically build messages, however, so needs to work with the "file descriptor set" and protoc was the only tool I found that generated that 🤷
